services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: ai-codebase-postgres
    environment:
      POSTGRES_USER: osk
      POSTGRES_PASSWORD: osk
      POSTGRES_DB: ai_codebase_explorer
    ports:
      - "5432:5432"

  redis:
    image: redis:8
    container_name: ai-codebase-redis
    ports:
      - "6379:6379"